@file:OptIn(ExperimentalWasmDsl::class)

import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpackConfig
import java.time.LocalDate

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
}

val generateBlogIndex = tasks.register<GenerateBlogIndex>("generateBlogIndex") {
    postsDir.set(layout.projectDirectory.dir("src/commonMain/composeResources/files/blog"))
    outputDir.set(layout.buildDirectory.dir("generated/blogIndex/kotlin"))
}

kotlin {
    wasmJs {
        browser {
            outputModuleName.set("composeApp")
            commonWebpackConfig {
                devServer = (devServer ?: KotlinWebpackConfig.DevServer()).apply {
                    static(project.projectDir.path)
                }
            }
        }
        binaries.executable()
    }

    android {
        namespace = "com.jasontoms"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
        androidResources {
            enable = true
        }
    }
    
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }
    
    sourceSets {
        commonMain {
            kotlin.srcDir(generateBlogIndex)
        }
        commonMain.dependencies {
            implementation(libs.androidx.lifecycle)
            implementation(libs.compose.runtime)
            implementation(libs.compose.animation)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.material3.windowSizeClass)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.coil)
            implementation(libs.coil.ktor)
            implementation(libs.kotlinx.datetime)
            implementation(libs.markdown.renderer.m3)
            implementation(libs.markdown.renderer.coil3)
            implementation(libs.navigation3.ui)
        }
        iosMain.dependencies {
            implementation(libs.ktor.darwin)
        }
        androidMain.dependencies {
            implementation("org.jetbrains.compose.ui:ui-tooling:1.12.0")
        }
        wasmJsMain.dependencies {
            implementation(libs.ktor.js)
        }
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.targets.js.ir.DefaultIncrementalSyncTask>().configureEach {
    outputs.upToDateWhen { false }
}

/**
 * Builds the list of blog posts from the markdown files in [postsDir], since Compose resources
 * can't list a directory at runtime.
 *
 * Each post is named after its date (`2026-09-21.md`), which is also its URL, and starts with
 * front matter holding its title:
 * ```
 * ---
 * title: My first post
 * ---
 * ```
 */
abstract class GenerateBlogIndex : DefaultTask() {
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val postsDir: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val files = postsDir.get().asFile.listFiles { file -> file.extension == "md" }.orEmpty()
        val posts = files
            .map { file ->
                val date = runCatching { LocalDate.parse(file.nameWithoutExtension) }.getOrElse {
                    throw GradleException("Blog post ${file.name} must be named after its date, like 2026-09-21.md")
                }
                date to readTitle(file)
            }
            .sortedByDescending { (date, _) -> date }

        val entries = posts.joinToString(separator = "") { (date, title) ->
            "    BlogPost(date = LocalDate(${date.year}, ${date.monthValue}, ${date.dayOfMonth}), title = \"${title.escaped()}\"),\n"
        }
        val output = outputDir.get().asFile.resolve("blog/GeneratedBlogPosts.kt")
        output.parentFile.mkdirs()
        output.writeText(
            """
            |// Generated by the generateBlogIndex Gradle task from composeResources/files/blog. Do not edit.
            |package blog
            |
            |import kotlinx.datetime.LocalDate
            |
            |/** Newest first. */
            |internal val generatedBlogPosts: List<BlogPost> = listOf(
            |$entries)
            |""".trimMargin()
        )
    }

    private fun readTitle(file: File): String {
        val lines = file.readLines()
        val end = lines.drop(1).indexOfFirst { it.trim() == "---" }
        if (lines.firstOrNull()?.trim() != "---" || end < 0) {
            throw GradleException("Blog post ${file.name} must start with front matter (a title between two --- lines)")
        }
        val title = lines.subList(1, end + 1)
            .map { it.split(":", limit = 2) }
            .firstOrNull { it.size == 2 && it[0].trim() == "title" }
            ?.get(1)?.trim()?.removeSurrounding("\"")
        if (title.isNullOrBlank()) throw GradleException("Blog post ${file.name} is missing a title in its front matter")
        return title
    }

    private fun String.escaped() = replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
}
